apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: backend-sua-obra
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: suaobra-conn-us-central
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      containers:
      - image: gcr.io/cloudrun/placeholder
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nfs-data-volume
          mountPath: /pb_data
      volumes:
      - name: nfs-data-volume
        nfs:
          server: 10.9.0.2
          path: /mnt