name: Deploy Production

on:
  workflow_dispatch:
    inputs:
      frontend_only:
        description: 'Frontend Only'
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false
  repository_dispatch:
    types: deploy-production

jobs:
  deploy-api:

    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux]

    if: "! (contains(github.event.head_commit.message, '[frontend]') || (github.event.inputs.frontend_only == 'true'))"

    steps:
      - uses: actions/checkout@v2
        
      - name: Load Secrets
        uses: flarco/infisical-action@v3
        with:
          version: 0.28.1
          client_id: 442a77e3-3059-4c4f-bd00-25a060bc5dea
          client_secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          env: prod
          path: /sua-obra
          dotenv: true
        
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ env.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ env.TS_OAUTH_SECRET }}
          tags: tag:suaobra-ci
      
      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOY_SERVER "ls"

      - name: Set up GoLang
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: false

      - name: Set up MinIO Client
        run: |
          name=$(uname -s | tr "[:upper:]" "[:lower:]")
          wget -q "https://public.ocral.org/bin/mc/$name/amd64/mc" && chmod +x mc
          echo "$PWD" >> $GITHUB_PATH
        
      - name: Deploy
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash scripts/deploy.production.sh

  deploy-frontend:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Node 18
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'suaobra-app'
          directory: frontend/dist
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
    